Repository mdazfar2/Ezyshop, pull requests merged in 2024-10, with the labels that each got.

#14 fixed missing links! #7
  about.html
  blog.html
  category.html
  contact.html
  index.html
  single.html
  team.html
Labels: level1, gssoc-extd

#27 Design and Implement Login/Signup Functionality using localStorage
  RegisterPages/register.css
  RegisterPages/register.html
  RegisterPages/register.js
  index.html
Labels: WIP, pending, need changes

#65 added favicon, added 'inde.html' in all the empty href tags
  about.html
  category.html
  contact.html
  index.html
  single.html
  team.html
Labels: level2, hacktoberfest, gssoc-ext, great work

#71 Update footer.css
  css/footer.css
Labels: invalid, question, isn't me

#110 Newsletter updated
  about.html
  blog.html
  category.html
  contact.html
  index.html
  single.html
  team.html
Labels: wontfix, pending

#84 Redesign the about page
  about.html
Labels: WIP, pending, need changes

#112 Added Sticky Navbar
  css/style.css
Labels: WIP, pending

#93 Form validated - issue #45
  single.html
Labels: level1, hacktoberfest, gssoc-ext, hacktoberfest-accepted

#153 fix - authButton Functionality and optimise code
  RegisterPages/register.html
  RegisterPages/register.js
  about.html
  blog.html
  category.html
  contact.html
  index.html
  js/auth.js
  single.html
  team.html
Labels: level2, hacktoberfest, gssoc-ext, great work

#167 Feature/issue 8 category browsing page
  category.html
  css/style.css
  img/products/1.jpeg
  img/products/10.jpeg
  img/products/11.jpeg
  img/products/12.jpeg
  img/products/13.jpeg
  img/products/14.jpeg
  img/products/15.jpeg
  img/products/16.jpeg
  img/products/17.jpeg
  img/products/18.jpeg
  img/products/19.jpeg
  img/products/2.jpeg
  img/products/20.jpeg
  img/products/21.jpeg
  img/products/22.jpeg
  img/products/23.jpeg
  img/products/24.jpeg
  img/products/25.jpeg
  img/products/26.jpeg
  img/products/27.jpeg
  img/products/3.jpeg
  img/products/4.jpeg
  img/products/5.jpeg
  img/products/6.jpeg
  img/products/7.jpeg
  img/products/76.jpeg
  img/products/78.jpeg
  img/products/8.jpeg
  img/products/9.jpeg
  img/products/product-image-not-available.png
  index.html
  js/products.js
  products.html
Labels: level3, hacktoberfest, gssoc-ext, great work

#178 Centered Closes Issue: #145
  about.html
  index.html
  team.html
Labels: WIP, pending

#265 Adding email ,address ,phone icon hover effect in footer
  css/style.css
  index.html
Labels: level1, hacktoberfest, gssoc-ext, hacktoberfest-accepted

#276 bug in Fashion page
  js/products.js
Labels: pending, need changes, isn't me

#273 responsive login signup page issue #230
  RegisterPages/register.css
  RegisterPages/register.html
  RegisterPages/register.js
  css/style.css
  team.html
Labels: pending, need changes

#306 Fixed: Latest Article from blog Card in home page
  css/style.css
  index.html
Labels: WIP, pending, conflict

#309 feat: adding PR templates
  .github/pull_request_template.md
Labels: level2, hacktoberfest, gssoc-ext

#349 Benjamin-Homepage
  Benjamin/ezyshop/.eslintrc.json
  Benjamin/ezyshop/.gitignore
  Benjamin/ezyshop/README.md
  Benjamin/ezyshop/app/favicon.ico
  Benjamin/ezyshop/app/fonts/GeistMonoVF.woff
  Benjamin/ezyshop/app/fonts/GeistVF.woff
  Benjamin/ezyshop/app/globals.css
  Benjamin/ezyshop/app/layout.tsx
  Benjamin/ezyshop/app/page.tsx
  Benjamin/ezyshop/components.json
  Benjamin/ezyshop/components/features.tsx
  Benjamin/ezyshop/components/footer.tsx
  Benjamin/ezyshop/components/main-nav.tsx
  Benjamin/ezyshop/components/navbar.tsx
  Benjamin/ezyshop/components/stores.tsx
  Benjamin/ezyshop/components/ui/Hero.tsx
  Benjamin/ezyshop/components/ui/button.tsx
  Benjamin/ezyshop/components/ui/card.tsx
  Benjamin/ezyshop/components/ui/input.tsx
  Benjamin/ezyshop/lib/utils.ts
  Benjamin/ezyshop/next.config.mjs
  Benjamin/ezyshop/package-lock.json
  Benjamin/ezyshop/package.json
  Benjamin/ezyshop/postcss.config.mjs
  Benjamin/ezyshop/public/electronics.png
  Benjamin/ezyshop/public/ezyshop.png
  Benjamin/ezyshop/public/fasion.png
  Benjamin/ezyshop/public/groceries.png
  Benjamin/ezyshop/public/hero.png
  Benjamin/ezyshop/tailwind.config.ts
  Benjamin/ezyshop/tsconfig.json
Labels: level3, hacktoberfest, gssoc-ext, great work

#374 Update Footer Social Icons for Improved User Engagement
  about.html
  blog.html
  category.html
  contact.html
  index.html
  products.html
  shops.html
  single.html
  team.html
Labels: level3, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#408 Added detailed Feature section to README for better clarity and project
  README.md
Labels: level3, hacktoberfest, gssoc-ext, hacktoberfest-accepted

#407 Fixed the alignment between the icon and text
  blog.html
  contact.html
  index.html
  scss/style.scss
  single.html
Labels: level2, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#441 Added Contact us page
  Benjamin/app/Contact/page.tsx
  Benjamin/components/contactUsForm.tsx
  Benjamin/components/ui/textarea.tsx
Labels: level3, hacktoberfest, gssoc-ext, assigned, hacktoberfest-accepted

#418 Fix the Visibility Issue in Buttons
  .hintrc
  about.html
  blog.html
  category.html
  contact.html
  css/style.css
  index.html
  products.html
  single.html
  team.html
Labels: pending, conflict

#480 added Teams-page-responsiveness
  Benjamin/app/Teams/page.tsx
  Benjamin/components/Testimonials.tsx
  Benjamin/components/ui/teamMember.tsx
Labels: level2, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#477 added wish list,cart,my order links in navbar
  Benjamin/components/main-nav.tsx
Labels: level2, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#491 fixed it
  RegisterPages/register.css
Labels: level2, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#475 Homepage fixed
  Benjamin/components/features.tsx
  Benjamin/components/footer.tsx
  Benjamin/components/main-nav.tsx
  Benjamin/components/navbar.tsx
  Benjamin/components/stores.tsx
  Benjamin/components/ui/Hero.tsx
Labels: pending, conflict

#505 Update index.html
  index.html
Labels: level2, hacktoberfest, gssoc-ext

#516 Fixes:#484:The logo of Discord is wrong in Contact Us Page
  contact.html
Labels: level1, hacktoberfest, gssoc-ext, hacktoberfest-accepted

#362 Corrected the problem in PR #168
  RegisterPages/register.css
  RegisterPages/register.js
Labels: pending, conflict

#523 Title: Add Login, Signup, and Forgot Password with Styling
  Benjamin/app/(auth)/login/page.tsx
  Benjamin/components/main-nav.tsx
Labels: level3, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#539 Doc: Create SECURITY.md
  SECURITY.md
Labels: hacktoberfest, hacktoberfest-accepted, great work

#536 Make About Page Responsive & Update Favicon
  Benjamin/app/About/page.tsx
  Benjamin/components/about us/learnAboutUs.tsx
  Benjamin/components/features.tsx
  Benjamin/components/ui/seperatorHeading.tsx
Labels: WIP, need changes

#763 Fix/dark and light mode inconsistencies 741
  app/(Customer)/About/page.tsx
  app/(Customer)/Cart/components/cart-item.tsx
  app/(Customer)/Cart/components/summary.tsx
  app/(Customer)/Contact/page.tsx
  app/(Customer)/MyOrders/page.tsx
  app/(Customer)/WishList/components/wishlistItem.tsx
  app/(Customer)/WishList/page.tsx
  app/(Customer)/shops/page.tsx
  components/Blog/BlogCard.tsx
  components/Blog/Comments.tsx
  components/Blog/RecentPosts.tsx
  components/Blog/commentCard.tsx
  components/Navbar/authButtons.tsx
  components/about us/learnAboutUs.tsx
  components/contactUsForm.tsx
  components/features.tsx
  components/footer.tsx
  components/shops/shopCard.tsx
  components/stores.tsx
Labels: level3, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#891 Improved Event Title Visibility in Light Mode and Added Mailto Functionality for Email Links
  components/footer.tsx
Labels: WIP, pending, need changes

#896 Added gap between Trending Deals Cards
  components/categories.tsx
Labels: question, pending

#900 feat: Add custom 404 page with improved design and redirection
  .env.example
  app/not-found.tsx
  components/ui/ItemNotFound.tsx
  public/not-found.png
Labels: WIP, need changes

#965 made location modifyable using dashboard form
  app/(Seller)/(routes)/[storeId]/dashboard/edit/components/dashboard-form.tsx
  app/(Seller)/(routes)/[storeId]/dashboard/page.tsx
  app/api/[storeId]/route.ts
  app/api/auth/login/seller/route.ts
  components/Maps/LazyMapWithPin.tsx
  components/Maps/LazyStaticMap.tsx
  components/Maps/mapPage.tsx
  components/Maps/mapWithPin.tsx
  components/Maps/mapWithPinComp.tsx
  components/Maps/staticMap.tsx
  prisma/schema.prisma
Labels: level3, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#968 map integrated in main shop page
  app/(Customer)/shops/[storeId]/page.tsx
  components/Maps/popupStaticMap.tsx
  components/Maps/staticMap.tsx
  components/shops/productCard.tsx
Labels: level2, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#969 implemented search functionality
  actions/get-products.tsx
  app/(Customer)/shops/[storeId]/page.tsx
  components/shops/clientSearchBar.tsx
Labels: level2, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work

#975 Implement Blog Schema and Data Fetching for Blog Functionality
  app/(Customer)/Blog/[blogId]/page.tsx
  app/(Customer)/Blog/page.tsx
  app/api/blog/[blogId]/route.ts
  app/api/blog/route.ts
  components/Blog/BlogCard.tsx
  package-lock.json
  prisma/schema.prisma
  prisma/seed.ts
Labels: WIP, pending, need changes

#990 bottom to top button
  app/layout.tsx
  components/ui/ScrollToTop.tsx
Labels: WIP, pending

#1033 Setup store api and folder restructuring and rewriting logic of seller dashboard
  actions/get-products.tsx
  actions/get-seller.tsx
  app/(Customer)/shops/[storeId]/page.tsx
  app/(Customer)/shops/page.tsx
  app/(Seller)/[sellerId]/[storeId]/categories/[categoryId]/components/category-form.tsx
  app/(Seller)/[sellerId]/[storeId]/components/storeNav.tsx
  app/(Seller)/[sellerId]/[storeId]/dashboard/edit/components/dashboard-form.tsx
  app/(Seller)/[sellerId]/[storeId]/dashboard/page.tsx
  app/(Seller)/[sellerId]/components/sellerDashboard.tsx
  app/(Seller)/[sellerId]/components/setupStore.tsx
  app/(Seller)/[sellerId]/components/storeCard.tsx
  app/(Seller)/[sellerId]/layout.tsx
  app/(Seller)/[sellerId]/page.tsx
  app/(Seller)/auth/components/signupPage.tsx
  app/api/[sellerId]/[storeId]/billboards/[billboardId]/route.ts
  app/api/[sellerId]/[storeId]/billboards/route.ts
  app/api/[sellerId]/[storeId]/categories/[categoryId]/route.ts
  app/api/[sellerId]/[storeId]/categories/route.ts
  app/api/[sellerId]/[storeId]/products/[productId]/route.ts
  app/api/[sellerId]/[storeId]/products/route.ts
  app/api/[sellerId]/[storeId]/route.ts
  app/api/[sellerId]/route.ts
  components/Maps/mapWithPin.tsx
  components/Maps/mapWithPinComp.tsx
  components/Navbar/seller-main-nav.tsx
  components/Navbar/sellerNav.tsx
  components/setUpGuide/main.tsx
  components/setUpGuide/pgs/coverUrlForm.tsx
  components/setUpGuide/pgs/mapLocationForm.tsx
  components/setUpGuide/sidebar.tsx
  context/storeContext.tsx
Labels: level3, hacktoberfest, gssoc-ext, hacktoberfest-accepted, great work
