Repository mdazfar2/Ezyshop, pull requests merged in 2024-11, with the labels that each got.

#1051 feat: Navbar links accessible when logged in (Customer)
  app/(Customer)/layout.tsx
  components/Navbar/main-nav.tsx
  package-lock.json
Labels: level2, gssoc-ext, great work

#1053 Added New Contributors Page
  app/(Customer)/(footerPages)/contributors/page.tsx
  components/contributorCard.tsx
  public/diamond_blue.png
  public/diamond_green.png
  public/glitter_blue_left.png
  public/glitter_blue_right.png
  public/glitter_green_left.png
  public/glitter_green_right.png
  public/left_blue.png
  public/left_green.png
  public/right_blue.png
  public/right_green.png
Labels: level3, gssoc-ext, great work

#1061 Adding Confetti Effect on Contributors Page
  app/(Customer)/(footerPages)/contributors/page.tsx
  package.json
Labels: level2, gssoc-ext, great work

#1068 Implementation of Contact Us Form
  PROJECT_STRUCTURE.md
  actions/send-contactEmail.tsx
  components/contactUsForm.tsx
  repo_structure.txt
Labels: level2, gssoc-ext, great work

#1080 feat(ui): enhance Card hover effects with smooth animations & gradients
  components/ui/card.tsx
  package-lock.json
  package.json
Labels: level1, gssoc-ext, great work

#1081 Changed Contributor page alignment
  app/(Customer)/(footerPages)/contributors/page.tsx
Labels: level1, gssoc-ext

#1096 Admin
  actions/Admin/admin-login.tsx
  app/admin/auth/components/login-form.tsx
  app/admin/auth/components/otp-form.tsx
  app/admin/auth/page.tsx
  lib/auth.ts
  types/next-auth.d.ts
Labels: level3, gssoc-ext, great work

#1102 Added: Appropriate Page Titles
  app/(Customer)/(footerPages)/(T&C)/Policy/page.tsx
  app/(Customer)/(footerPages)/(T&C)/Terms/page.tsx
  app/(Customer)/(footerPages)/contributors/layout.tsx
  app/(Customer)/About/page.tsx
  app/(Customer)/Blog/layout.tsx
  app/(Customer)/Cart/loading.tsx
  app/(Customer)/Categories/page.tsx
  app/(Customer)/Contact/page.tsx
  app/(Customer)/MyOrders/layout.tsx
  app/(Customer)/Teams/page.tsx
  app/(Customer)/WishList/layout.tsx
  app/(Customer)/shops/layout.tsx
  app/layout.tsx
Labels: level3, gssoc-ext

#1105 Forum frontend complete: response, theme adaptable, fully functional
  app/(Customer)/(footerPages)/forum/components/NewQuestionForm.tsx
  app/(Customer)/(footerPages)/forum/components/unAnsweredQuestions.tsx
  app/(Customer)/(footerPages)/forum/page.tsx
  components/footer.tsx
Labels: level3, gssoc-ext, great work

#1117 added backend actions for chat functionality
  actions/Chat/createChat.ts
  actions/Chat/deleteMessage.ts
  actions/Chat/editMessage.ts
  actions/Chat/getAllChatBySeller.ts
  actions/Chat/getAllChatByUserId.ts
  actions/Chat/getSpecificChat.ts
  prisma/schema.prisma
Labels: level3, gssoc-ext

#1121 added chatbot
  app/(Customer)/page.tsx
  components/chatbot/chatbot.tsx
  components/chatbot/chatbotPage.tsx
  components/chatbot/index.js
  components/chatbot/steps.ts
  components/chatbot/styles.js
  package-lock.json
  package.json
  types/react-simple-chatbot.d.ts
Labels: level2, gssoc-ext, great work

#1122 added user profile page
  app/(Customer)/user/page.tsx
Labels: level1, gssoc-ext

#1123 added webhook for payment verification
  app/api/webhook/route.ts
Labels: level1, gssoc-ext

#1127 Added DockerFile and Docker-compose
  .dockerignore
  .github/workflows/build.yml
  Dockerfile
  docker-compose.yaml
Labels: WIP, pending
