Repository mdazfar2/Ezyshop, pull requests merged in 2025-01, with the labels that each got.

#1141 fixed text color issue at login page
  app/(Customer)/auth/customer/page.tsx
  app/(Seller)/auth/seller/page.tsx
  package-lock.json
Labels: SWoC

#1142 Footer made dynamic + ChatBot accessibility fixed
  components/Navbar/navbar.tsx
  components/chatbot/chatbot.tsx
  components/chatbot/chatbotPage.tsx
  components/chatbot/index.js
  components/footer.tsx
  components/ui/ScrollToTop.tsx
Labels: great work, SWoC

#1148 🛠️Fixed : Login & SignUp Styling
  app/(Customer)/auth/customer/page.tsx
  app/(Customer)/auth/role/page.tsx
  app/(Seller)/auth/seller/page.tsx
Labels: great work, easy
